- name: Download Grafana OSS .deb package
  get_url:
    url: "https://dl.grafana.com/oss/release/grafana_10.0.2_amd64.deb"
    dest: "/tmp/grafana_10.0.2_amd64.deb"

- name: Install Grafana OSS (Ubuntu)
  become: true
  apt:
    deb: "/tmp/grafana_10.0.2_amd64.deb"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: "/etc/grafana/grafana.ini"
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Check if Grafana is accessible."
  uri:
    url: "http://44.202.239.26:3000"  
    method: GET
    status_code: 200
